[theme]
base = "light"  # Use "dark" for dark mode
primaryColor = "#1DB954"  # Spotify green
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f5f5f5"
textColor = "#262730"
font = "sans serif"


